# Generated by Django 5.0.5 on 2024-05-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fullname',
            new_name='Affiliation',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='Approved',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='email',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.AddField(
            model_name='member',
            name='BackupEmail',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='BoardRegNo',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='DateRegistration',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='Designation',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='Fullname',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='IDNumber',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='MemberNo',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='Phone',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='PostalAddress',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='PostalCode',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='Roles',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='Status',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='SubSpecialization',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='TownorCity',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='Workstation',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
