# Generated by Django 5.0.5 on 2024-05-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_boardregno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Approved',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='BoardRegNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='DateRegistration',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='IDNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='MemberNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='PostalCode',
            field=models.IntegerField(null=True),
        ),
    ]
