# Generated by Django 5.0.5 on 2024-05-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_member_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DateRegistration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='IDNumber',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='MemberNo',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='Phone',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
