# Generated by Django 5.0.5 on 2024-05-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_member_approved_alter_member_boardregno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='BackupEmail',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='BoardRegNo',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='DateRegistration',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='Phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='PostalAddress',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='PostalCode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
