# Generated by Django 5.0.5 on 2024-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_member_approved_alter_member_backupemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='DateRegistration',
        ),
        migrations.AlterField(
            model_name='member',
            name='Approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
