# Generated by Django 5.0.5 on 2024-05-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_member_dateregistration_alter_member_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='DateRegistration',
            field=models.DateField(default=' '),
            preserve_default=False,
        ),
    ]
