# Generated by Django 5.0.5 on 2024-05-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_dateregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DateRegistration',
            field=models.DateField(null=True),
        ),
    ]
