# Generated by Django 5.0.5 on 2024-05-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_member_dateregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='DateRegistration',
        ),
    ]
