# Generated by Django 5.0.5 on 2024-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_member_dateregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DateRegistration',
            field=models.DateField(blank=True, default=' ', null=True),
        ),
    ]
