# Generated by Django 5.0.5 on 2024-05-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_rename_dateregistration_member_dateregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Dateregistration',
            new_name='DateRegistration',
        ),
    ]
