# Generated by Django 5.0.5 on 2024-05-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_rename_dateregistration_member_dateregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Approved',
            field=models.CharField(max_length=100),
        ),
    ]
