# Generated by Django 5.0.5 on 2024-05-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_alter_member_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
